### ISSUE TITLE
Why is pip install wav2lip written?

### ISSUE THREAD

**Issue by Rudrabha** [dheerajmpai/saenews#4]
![image](https://user-images.githubusercontent.com/35054375/93296148-3d4d6600-f80c-11ea-94e1-5bb3e592ba1e.png)

I got redirected to this repository from the package that is attached in the pic. Any idea why the name "wav2lip" is being used?

**Comment by dheerajmpai** [comment]
Hey @Rudrabha, I am planning to make a pypi library [Wav2Lip](https://github.com/Rudrabha/Wav2Lip) research. While I am still working on it I felt it would be better to reserve the pypi package name (considering the publicity). If you are also working on making a Pypi packages I will just transfer the name to you. It's totally my fault (inefficiency and delay) that I failed to complete the packaging on time.

**Comment by Rudrabha** [comment]
Hello,
We would like to have the name for ourselves as we wanted to create a pypi package ourselves. You are more than welcome to contribute in that package.
